// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZRenPYDH8HtBYC2LOVNfbLguGWjAM-s',
    appId: '1:437514049573:web:ae69cd74682481d52987cc',
    messagingSenderId: '437514049573',
    projectId: 'chessapp-359f2',
    authDomain: 'chessapp-359f2.firebaseapp.com',
    storageBucket: 'chessapp-359f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4Zdn6CCV3BBP85wPLUERS8upDVG3YvY',
    appId: '1:437514049573:android:1f0f8b90e8f1f1762987cc',
    messagingSenderId: '437514049573',
    projectId: 'chessapp-359f2',
    storageBucket: 'chessapp-359f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw35LwinJAcN2yMUkTd__PG4IRJZaZnOA',
    appId: '1:437514049573:ios:79c9e87f1a1eab762987cc',
    messagingSenderId: '437514049573',
    projectId: 'chessapp-359f2',
    storageBucket: 'chessapp-359f2.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw35LwinJAcN2yMUkTd__PG4IRJZaZnOA',
    appId: '1:437514049573:ios:79c9e87f1a1eab762987cc',
    messagingSenderId: '437514049573',
    projectId: 'chessapp-359f2',
    storageBucket: 'chessapp-359f2.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlZRenPYDH8HtBYC2LOVNfbLguGWjAM-s',
    appId: '1:437514049573:web:4a4d13cb65a037952987cc',
    messagingSenderId: '437514049573',
    projectId: 'chessapp-359f2',
    authDomain: 'chessapp-359f2.firebaseapp.com',
    storageBucket: 'chessapp-359f2.firebasestorage.app',
  );
}
